// -----------------------------------------------------------------------
// <copyright file="201804030649414_DeploymentFileds.Designer.cs" company="Microsoft">
//      Copyright (c) Microsoft Corporation.  All rights reserved.
// </copyright>
// -----------------------------------------------------------------------

// <auto-generated />
namespace ServiceCatalog.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class DeploymentFileds : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(DeploymentFileds));
        
        string IMigrationMetadata.Id
        {
            get { return "201804030649414_DeploymentFileds"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
